# Generated by Django 4.1.3 on 2022-11-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Qna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "answer",
                    models.CharField(
                        choices=[
                            ("question1", "Question1"),
                            ("question2", "Question2"),
                        ],
                        max_length=255,
                        verbose_name="Answer",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
